# Generated by Django 3.2 on 2021-11-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='clap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='love',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loves', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='blog.blogpost'),
        ),
    ]
