# Generated by Django 3.2 on 2021-11-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211121_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='clap',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='love',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='read',
        ),
        migrations.CreateModel(
            name='BlogReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='blog.blogpost')),
                ('love', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loves', to='blog.blogpost')),
                ('read', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='blog.blogpost')),
            ],
        ),
    ]
