# Generated by Django 3.2 on 2022-02-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211127_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
