# Generated by Django 3.2 on 2022-02-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmessage',
            options={'managed': True},
        ),
    ]
