# Generated by Django 3.2 on 2022-02-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmessage',
            name='post',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
