# Generated by Django 3.2 on 2022-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogmessage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmessage',
            name='post',
            field=models.CharField(max_length=120),
        ),
    ]
